# app/config/api_platform/resources/

App\Entity\Comment:
  attributes: 
    security: is_granted("ROLE_USER")
    denormalization_context:
      groups: [write:Comment, update:Comment]
    normalization_context:
      groups: ['read:Movie:item']

  collectionOperations:
    post: 

  itemOperations:
    get: ~
    put:
      # security: 'is_granted("EDIT", object)' # later : voter
      openapi_context:
        responses:
            403:
              description: Access Denied
    delete:
      # security: 'is_granted("DELETE", object)' # later : voter
      openapi_context:
        responses:
            403:
              description: Access Denied
