# app/config/api_platform/resources/

App\Entity\Rent:
  attributes: 
    security: is_granted("ROLE_USER")
    denormalization_context:
      groups: [write:Rent]
    normalization_context:
      groups: ['read:Rent:item']
      
  collectionOperations:
    post:

  itemOperations:
    get: ~
    # security: 'is_granted("SHOW", object)' # later : voter

