# app/config/api_platform/resources/

App\Entity\Rent:
  attributes: 
    security: is_granted("ROLE_USER")
  denormalization_context:
    groups: [write:Movie]
    openapi_definition_name: Item

  collectionOperations:
    post:  
  itemOperations:
    put:
      security: 'is_granted("ROLE_ADMIN")'
      openapi_context:
        summary: Admin Only.
        responses:
            403:
              description: Access Denied
    patch:
      security: 'is_granted("ROLE_ADMIN")'
      openapi_context:
        summary: Admin Only.
        responses:
            403:
              description: Access Denied
    delete:
      security: 'is_granted("ROLE_ADMIN")'
      openapi_context:
        summary: Admin Only.
        responses:
            403:
              description: Access Denied
